# Etape 1 : build avec Maven
FROM maven AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DSkipTests 
#skiptest permet d'ignorer les tests. Dans le /app on aura un fichier .jar

# Etape 2 : image d'execution
FROM eclipse-temurin
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8111
ENTRYPOINT [ "java","-jar","app.jar" ]
